sudo: required
language: generic
services:
  - docker

before_install:
  - docker build -t mearaj/docker-react -f ./Section6/frontend/Dockerfile.dev ./Section6/frontend

script:
  - docker run -e CI=true mearaj/docker-react npm run test